Se agregan cambios para agregarlos a aws
brain-espaciocreativo/TBM pull request #88
Opened 2022-12-15 20:04 UTC by YoelFerreyra

2022-12-15 20:51 UTC, tzanuttini commented on web/src/components/news/NewsForm.jsx
> +            url: `http://ec2-18-228-222-33.sa-east-1.compute.amazonaws.com:3000/news?name=${data.name}&description=${data.description}&workId=${selectWork}`,
Borrate esto porfis, dejalo con localhost

2022-12-15 20:51 UTC, tzanuttini requested changes
Porfa cambiame el endpoint

2022-12-16 22:04 UTC, BrayannFarfan approved these changes

2022-12-17 23:35 UTC, tzanuttini approved these changes

2022-12-22 12:44 UTC, merged